# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeHGciIkibT3o_Dj_Ci67KXZUryEHGSe
"""

# Importing libraries

import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

df=pd.read_csv("data/train.csv")

df.tail()

df.tweet=df.tweet.str.split(" ")

nltk.download('stopwords')
df.tail()

stop_words = set(stopwords.words('english'))

df['tweet']

df['tweet']=df['tweet'].apply(lambda x: [item for item in x if item not in stop_words])
df['tweet']

df['tweet']=df['tweet'].apply(lambda x: collections.Counter(x))
df['tweet']

df.tail()











"""SENTIMENT ANALYSIS"""

with open('sample_data/all_balanced.txt') as f:
    text_data = f.readlines()

raw_data = pd.DataFrame(text_data, columns = ['words'])
raw_data

raw_data = raw_data.replace({'_':' '}, regex=True)
raw_data

stop_words = set(stopwords.words('english'))